-- ================================================================
--  ███╗   ███╗ █████╗ ██╗   ██╗███████╗███╗   ██╗
--  ████╗ ████║██╔══██╗██║   ██║██╔════╝████╗  ██║
--  ██╔████╔██║███████║██║   ██║█████╗  ██╔██╗ ██║
--  ██║╚██╔╝██║██╔══██║╚██╗ ██╔╝██╔══╝  ██║╚██╗██║
--  ██║ ╚═╝ ██║██║  ██║ ╚████╔╝ ███████╗██║ ╚████║
--  ╚═╝     ╚═╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═══╝
-- ================================================================
--  MAVEN FUZZY FACTORY | MASTER SQL PROJECT FILE
-- ================================================================
--  Project      : End-to-End E-Commerce Data Analyst Portfolio
--  Database     : PostgreSQL
--  Author       : Saket Tripathi
--  Date         : 2026
--  Dataset      : Maven Fuzzy Factory (E-Commerce Toy Retailer)
-- ================================================================
--
--  TABLE OF CONTENTS
--  -----------------
--  STEP 1 : Database Schema (DDL)
--  STEP 2 : Data Loading
--  STEP 3 : Complex JOINs & Subqueries
--  STEP 4 : Window Functions & CTEs
--  STEP 5 : Stored Procedures & Triggers
--  STEP 6 : Performance Optimization & Indexing
--
--  DATASET SUMMARY
--  ---------------
--  products            →       4 rows
--  website_sessions    → 472,871 rows
--  website_pageviews   → 1,188,124 rows
--  orders              →  32,313 rows
--  order_items         →  40,025 rows
--  order_item_refunds  →   1,731 rows
--  TOTAL               → 1,735,068 rows
-- ================================================================

SET search_path TO public;


-- ================================================================
-- ████████████████████████████████████████████████████████████████
--   STEP 1 : DATABASE SCHEMA
-- ████████████████████████████████████████████████████████████████
-- ================================================================

-- ============================================================
-- TABLE 1: products
-- ============================================================
CREATE TABLE products (
    product_id      INT             GENERATED BY DEFAULT AS IDENTITY,
    created_at      TIMESTAMP       NOT NULL,
    product_name    VARCHAR(100)    NOT NULL,

    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

-- ============================================================
-- TABLE 2: website_sessions
-- ============================================================
CREATE TABLE website_sessions (
    website_session_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    created_at          TIMESTAMP       NOT NULL,
    user_id             BIGINT          NOT NULL,
    is_repeat_session   BOOLEAN         NOT NULL DEFAULT FALSE,
    utm_source          VARCHAR(50),
    utm_campaign        VARCHAR(50),
    utm_content         VARCHAR(50),
    device_type         VARCHAR(20),
    http_referer        VARCHAR(200),

    CONSTRAINT pk_website_sessions PRIMARY KEY (website_session_id)
);

-- ============================================================
-- TABLE 3: website_pageviews
-- ============================================================
CREATE TABLE website_pageviews (
    website_pageview_id BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    created_at          TIMESTAMP       NOT NULL,
    website_session_id  BIGINT          NOT NULL,
    pageview_url        VARCHAR(200)    NOT NULL,

    CONSTRAINT pk_website_pageviews  PRIMARY KEY (website_pageview_id),
    CONSTRAINT fk_pageviews_session  FOREIGN KEY (website_session_id)
        REFERENCES website_sessions (website_session_id)
);

-- ============================================================
-- TABLE 4: orders
-- ============================================================
CREATE TABLE orders (
    order_id            INT             GENERATED BY DEFAULT AS IDENTITY,
    created_at          TIMESTAMP       NOT NULL,
    website_session_id  BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    primary_product_id  INT             NOT NULL,
    items_purchased     SMALLINT        NOT NULL DEFAULT 1,
    price_usd           DECIMAL(6,2)    NOT NULL,
    cogs_usd            DECIMAL(6,2)    NOT NULL,

    CONSTRAINT pk_orders             PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_session     FOREIGN KEY (website_session_id)
        REFERENCES website_sessions (website_session_id),
    CONSTRAINT fk_orders_product     FOREIGN KEY (primary_product_id)
        REFERENCES products (product_id),

    CONSTRAINT chk_price_positive    CHECK (price_usd > 0),
    CONSTRAINT chk_cogs_positive     CHECK (cogs_usd > 0),
    CONSTRAINT chk_cogs_lt_price     CHECK (cogs_usd < price_usd)
);

-- ============================================================
-- TABLE 5: order_items
-- ============================================================
CREATE TABLE order_items (
    order_item_id   INT             GENERATED BY DEFAULT AS IDENTITY,
    created_at      TIMESTAMP       NOT NULL,
    order_id        INT             NOT NULL,
    product_id      INT             NOT NULL,
    is_primary_item BOOLEAN         NOT NULL DEFAULT FALSE,
    price_usd       DECIMAL(6,2)    NOT NULL,
    cogs_usd        DECIMAL(6,2)    NOT NULL,

    CONSTRAINT pk_order_items        PRIMARY KEY (order_item_id),
    CONSTRAINT fk_items_order        FOREIGN KEY (order_id)
        REFERENCES orders (order_id),
    CONSTRAINT fk_items_product      FOREIGN KEY (product_id)
        REFERENCES products (product_id),

    CONSTRAINT chk_item_price        CHECK (price_usd > 0),
    CONSTRAINT chk_item_cogs         CHECK (cogs_usd > 0)
);

-- ============================================================
-- TABLE 6: order_item_refunds
-- ============================================================
CREATE TABLE order_item_refunds (
    order_item_refund_id    INT             GENERATED BY DEFAULT AS IDENTITY,
    created_at              TIMESTAMP       NOT NULL,
    order_item_id           INT             NOT NULL,
    order_id                INT             NOT NULL,
    refund_amount_usd       DECIMAL(6,2)    NOT NULL,

    CONSTRAINT pk_order_item_refunds PRIMARY KEY (order_item_refund_id),
    CONSTRAINT fk_refunds_order_item FOREIGN KEY (order_item_id)
        REFERENCES order_items (order_item_id),
    CONSTRAINT fk_refunds_order      FOREIGN KEY (order_id)
        REFERENCES orders (order_id),

    CONSTRAINT chk_refund_positive   CHECK (refund_amount_usd > 0)
);


-- ================================================================
-- ████████████████████████████████████████████████████████████████
--   STEP 2 : DATA LOADING
-- ████████████████████████████████████████████████████████████████
-- ================================================================

-- ============================================================
-- IMPORTANT: Load Order (Parent tables before child tables)
-- 1. products             (no dependencies)
-- 2. website_sessions     (no dependencies)
-- 3. website_pageviews    (depends on website_sessions)
-- 4. orders               (depends on website_sessions, products)
-- 5. order_items          (depends on orders, products)
-- 6. order_item_refunds   (depends on order_items, orders)
-- ============================================================

-- Temporarily disable FK checks during bulk load
SET session_replication_role = 'replica';

-- Load products
COPY products (product_id, created_at, product_name)
FROM 'C:/Users/YourName/Downloads/products.csv'
DELIMITER ',' CSV HEADER;

SELECT setval(pg_get_serial_sequence('products', 'product_id'), MAX(product_id)) FROM products;

-- Load website_sessions
COPY website_sessions (
    website_session_id, created_at, user_id, is_repeat_session,
    utm_source, utm_campaign, utm_content, device_type, http_referer
)
FROM 'C:/Users/YourName/Downloads/website_sessions.csv'
DELIMITER ',' CSV HEADER;

SELECT setval(pg_get_serial_sequence('website_sessions', 'website_session_id'), MAX(website_session_id)) FROM website_sessions;

-- Load website_pageviews
COPY website_pageviews (website_pageview_id, created_at, website_session_id, pageview_url)
FROM 'C:/Users/YourName/Downloads/website_pageviews.csv'
DELIMITER ',' CSV HEADER;

SELECT setval(pg_get_serial_sequence('website_pageviews', 'website_pageview_id'), MAX(website_pageview_id)) FROM website_pageviews;

-- Load orders
COPY orders (
    order_id, created_at, website_session_id, user_id,
    primary_product_id, items_purchased, price_usd, cogs_usd
)
FROM 'C:/Users/YourName/Downloads/orders.csv'
DELIMITER ',' CSV HEADER;

SELECT setval(pg_get_serial_sequence('orders', 'order_id'), MAX(order_id)) FROM orders;

-- Load order_items
COPY order_items (
    order_item_id, created_at, order_id, product_id,
    is_primary_item, price_usd, cogs_usd
)
FROM 'C:/Users/YourName/Downloads/order_items.csv'
DELIMITER ',' CSV HEADER;

SELECT setval(pg_get_serial_sequence('order_items', 'order_item_id'), MAX(order_item_id)) FROM order_items;

-- Load order_item_refunds
COPY order_item_refunds (
    order_item_refund_id, created_at, order_item_id,
    order_id, refund_amount_usd
)
FROM 'C:/Users/YourName/Downloads/order_item_refunds.csv'
DELIMITER ',' CSV HEADER;

SELECT setval(pg_get_serial_sequence('order_item_refunds', 'order_item_refund_id'), MAX(order_item_refund_id)) FROM order_item_refunds;

-- Re-enable FK checks
SET session_replication_role = 'origin';

-- Verify row counts after loading
SELECT 'products'            AS table_name, COUNT(*) AS row_count FROM products
UNION ALL
SELECT 'website_sessions'    AS table_name, COUNT(*) AS row_count FROM website_sessions
UNION ALL
SELECT 'website_pageviews'   AS table_name, COUNT(*) AS row_count FROM website_pageviews
UNION ALL
SELECT 'orders'              AS table_name, COUNT(*) AS row_count FROM orders
UNION ALL
SELECT 'order_items'         AS table_name, COUNT(*) AS row_count FROM order_items
UNION ALL
SELECT 'order_item_refunds'  AS table_name, COUNT(*) AS row_count FROM order_item_refunds;

-- Expected:
-- products            →       4 rows
-- website_sessions    → 472,871 rows
-- website_pageviews   → 1,188,124 rows
-- orders              →  32,313 rows
-- order_items         →  40,025 rows
-- order_item_refunds  →   1,731 rows


-- ================================================================
-- ████████████████████████████████████████████████████████████████
--   STEP 3 : COMPLEX JOINs & SUBQUERIES
-- ████████████████████████████████████████████████████████████████
-- ================================================================

-- ============================================================
-- QUERY 1: Total Revenue, Cost & Profit by Product
-- Business Question: Which products are the most profitable?
-- ============================================================
SELECT
    p.product_name,
    COUNT(DISTINCT o.order_id)              AS total_orders,
    SUM(oi.price_usd)                       AS total_revenue,
    SUM(oi.cogs_usd)                        AS total_cost,
    SUM(oi.price_usd - oi.cogs_usd)         AS total_profit,
    ROUND(
        SUM(oi.price_usd - oi.cogs_usd) /
        SUM(oi.price_usd) * 100, 2
    )                                        AS profit_margin_pct
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_profit DESC;


-- ============================================================
-- QUERY 2: Monthly Revenue Trend
-- Business Question: How has revenue grown month over month?
-- ============================================================
SELECT
    DATE_TRUNC('month', o.created_at)       AS order_month,
    COUNT(DISTINCT o.order_id)              AS total_orders,
    SUM(o.price_usd)                        AS total_revenue,
    SUM(o.price_usd - o.cogs_usd)           AS total_profit,
    ROUND(AVG(o.price_usd), 2)              AS avg_order_value
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY DATE_TRUNC('month', o.created_at)
ORDER BY order_month;


-- ============================================================
-- QUERY 3: Refund Rate by Product
-- Business Question: Which products have the highest refund rates?
-- ============================================================
SELECT
    p.product_name,
    COUNT(DISTINCT oi.order_item_id)        AS total_items_sold,
    COUNT(DISTINCT r.order_item_refund_id)  AS total_refunds,
    ROUND(
        COUNT(DISTINCT r.order_item_refund_id)::DECIMAL /
        NULLIF(COUNT(DISTINCT oi.order_item_id), 0) * 100, 2
    )                                        AS refund_rate_pct,
    SUM(COALESCE(r.refund_amount_usd, 0))   AS total_refund_amount
FROM order_items oi
JOIN products p         ON oi.product_id = p.product_id
LEFT JOIN order_item_refunds r ON oi.order_item_id = r.order_item_id
GROUP BY p.product_name
ORDER BY refund_rate_pct DESC;


-- ============================================================
-- QUERY 4: Cross-Sell Analysis
-- Business Question: Which products are bought together most often?
-- ============================================================
SELECT
    p1.product_name                         AS primary_product,
    p2.product_name                         AS cross_sell_product,
    COUNT(*)                                AS times_bought_together
FROM order_items oi1
JOIN order_items oi2 ON oi1.order_id = oi2.order_id
                     AND oi1.product_id != oi2.product_id
                     AND oi1.is_primary_item = TRUE
                     AND oi2.is_primary_item = FALSE
JOIN products p1 ON oi1.product_id = p1.product_id
JOIN products p2 ON oi2.product_id = p2.product_id
GROUP BY p1.product_name, p2.product_name
ORDER BY times_bought_together DESC;


-- ============================================================
-- QUERY 5: Top Traffic Sources by Revenue
-- Business Question: Which marketing channels drive the most revenue?
-- ============================================================
SELECT
    COALESCE(ws.utm_source, 'direct')       AS traffic_source,
    COALESCE(ws.utm_campaign, 'none')       AS campaign,
    ws.device_type,
    COUNT(DISTINCT o.order_id)              AS total_orders,
    SUM(o.price_usd)                        AS total_revenue,
    ROUND(AVG(o.price_usd), 2)              AS avg_order_value
FROM orders o
JOIN website_sessions ws ON o.website_session_id = ws.website_session_id
GROUP BY
    COALESCE(ws.utm_source, 'direct'),
    COALESCE(ws.utm_campaign, 'none'),
    ws.device_type
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 6: Conversion Rate by Traffic Source
-- Business Question: Which traffic source converts best?
-- ============================================================
SELECT
    COALESCE(ws.utm_source, 'direct')       AS traffic_source,
    COUNT(DISTINCT ws.website_session_id)   AS total_sessions,
    COUNT(DISTINCT o.order_id)              AS total_orders,
    ROUND(
        COUNT(DISTINCT o.order_id)::DECIMAL /
        NULLIF(COUNT(DISTINCT ws.website_session_id), 0) * 100, 2
    )                                        AS conversion_rate_pct
FROM website_sessions ws
LEFT JOIN orders o ON ws.website_session_id = o.website_session_id
GROUP BY COALESCE(ws.utm_source, 'direct')
ORDER BY conversion_rate_pct DESC;


-- ============================================================
-- QUERY 7: Repeat vs New Customer Revenue
-- Business Question: How much revenue comes from repeat customers?
-- ============================================================
SELECT
    CASE
        WHEN ws.is_repeat_session = TRUE THEN 'Repeat Customer'
        ELSE 'New Customer'
    END                                     AS customer_type,
    COUNT(DISTINCT o.order_id)              AS total_orders,
    SUM(o.price_usd)                        AS total_revenue,
    ROUND(AVG(o.price_usd), 2)              AS avg_order_value,
    ROUND(
        COUNT(DISTINCT o.order_id)::DECIMAL /
        SUM(COUNT(DISTINCT o.order_id)) OVER() * 100, 2
    )                                        AS order_share_pct
FROM orders o
JOIN website_sessions ws ON o.website_session_id = ws.website_session_id
GROUP BY ws.is_repeat_session
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 8: Clean vs Refunded Orders
-- Business Question: What percentage of orders were refunded?
-- ============================================================
SELECT
    order_status,
    COUNT(*)                                AS total_orders,
    SUM(total_revenue)                      AS total_revenue,
    ROUND(
        COUNT(*)::DECIMAL /
        SUM(COUNT(*)) OVER() * 100, 2
    )                                        AS pct_of_orders
FROM (
    SELECT
        o.order_id,
        o.price_usd                         AS total_revenue,
        CASE
            WHEN r.order_id IS NOT NULL THEN 'Refunded'
            ELSE 'Clean'
        END                                 AS order_status
    FROM orders o
    LEFT JOIN order_item_refunds r ON o.order_id = r.order_id
) AS order_summary
GROUP BY order_status
ORDER BY total_orders DESC;


-- ================================================================
-- ████████████████████████████████████████████████████████████████
--   STEP 4 : WINDOW FUNCTIONS & CTEs
-- ████████████████████████████████████████████████████████████████
-- ================================================================

-- ============================================================
-- QUERY 1: Running Total Revenue Over Time
-- Business Question: What is our cumulative revenue growth?
-- ============================================================
SELECT
    DATE_TRUNC('month', o.created_at)           AS order_month,
    SUM(o.price_usd)                            AS monthly_revenue,
    SUM(SUM(o.price_usd))
        OVER (ORDER BY DATE_TRUNC('month', o.created_at))
                                                AS running_total_revenue
FROM orders o
GROUP BY DATE_TRUNC('month', o.created_at)
ORDER BY order_month;


-- ============================================================
-- QUERY 2: Month Over Month Revenue Growth
-- Business Question: Is revenue growing or declining each month?
-- ============================================================
WITH monthly_revenue AS (
    SELECT
        DATE_TRUNC('month', created_at)         AS order_month,
        SUM(price_usd)                          AS total_revenue
    FROM orders
    GROUP BY DATE_TRUNC('month', created_at)
)
SELECT
    order_month,
    total_revenue,
    LAG(total_revenue) OVER
        (ORDER BY order_month)                  AS prev_month_revenue,
    ROUND(
        (total_revenue - LAG(total_revenue)
            OVER (ORDER BY order_month)) /
        LAG(total_revenue)
            OVER (ORDER BY order_month) * 100
    , 2)                                        AS mom_growth_pct
FROM monthly_revenue
ORDER BY order_month;


-- ============================================================
-- QUERY 3: Product Revenue Ranking Per Year
-- Business Question: How does each product rank by revenue?
-- ============================================================
SELECT
    p.product_name,
    DATE_TRUNC('year', oi.created_at)           AS order_year,
    SUM(oi.price_usd)                           AS total_revenue,
    RANK() OVER (
        PARTITION BY DATE_TRUNC('year', oi.created_at)
        ORDER BY SUM(oi.price_usd) DESC
    )                                           AS revenue_rank
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name, DATE_TRUNC('year', oi.created_at)
ORDER BY order_year, revenue_rank;


-- ============================================================
-- QUERY 4: Customer Order Frequency Analysis
-- Business Question: How many orders does each customer place?
-- ============================================================
WITH customer_orders AS (
    SELECT
        user_id,
        order_id,
        created_at,
        price_usd,
        COUNT(order_id) OVER
            (PARTITION BY user_id)              AS total_orders_by_customer,
        SUM(price_usd) OVER
            (PARTITION BY user_id)              AS total_spent_by_customer,
        RANK() OVER (
            PARTITION BY user_id
            ORDER BY created_at
        )                                       AS order_sequence
    FROM orders
)
SELECT
    total_orders_by_customer                    AS orders_placed,
    COUNT(DISTINCT user_id)                     AS number_of_customers,
    ROUND(AVG(total_spent_by_customer), 2)      AS avg_total_spent
FROM customer_orders
WHERE order_sequence = 1
GROUP BY total_orders_by_customer
ORDER BY total_orders_by_customer DESC;


-- ============================================================
-- QUERY 5: Top 3 Revenue Days Per Month
-- Business Question: What are the peak sales days each month?
-- ============================================================
WITH daily_revenue AS (
    SELECT
        DATE_TRUNC('month', created_at)         AS order_month,
        DATE_TRUNC('day', created_at)           AS order_day,
        SUM(price_usd)                          AS daily_revenue
    FROM orders
    GROUP BY
        DATE_TRUNC('month', created_at),
        DATE_TRUNC('day', created_at)
),
ranked_days AS (
    SELECT
        order_month,
        order_day,
        daily_revenue,
        RANK() OVER (
            PARTITION BY order_month
            ORDER BY daily_revenue DESC
        )                                       AS day_rank
    FROM daily_revenue
)
SELECT
    order_month,
    order_day,
    daily_revenue,
    day_rank
FROM ranked_days
WHERE day_rank <= 3
ORDER BY order_month, day_rank;


-- ============================================================
-- QUERY 6: Product Performance vs Average
-- Business Question: Which products perform above average?
-- ============================================================
WITH product_revenue AS (
    SELECT
        p.product_name,
        SUM(oi.price_usd)                       AS total_revenue,
        AVG(SUM(oi.price_usd)) OVER ()          AS avg_revenue_all_products
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY p.product_name
)
SELECT
    product_name,
    total_revenue,
    ROUND(avg_revenue_all_products, 2)          AS avg_revenue,
    ROUND(total_revenue - avg_revenue_all_products, 2)
                                                AS variance_from_avg,
    CASE
        WHEN total_revenue > avg_revenue_all_products THEN 'Above Average'
        WHEN total_revenue = avg_revenue_all_products THEN 'At Average'
        ELSE 'Below Average'
    END                                         AS performance_flag
FROM product_revenue
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 7: Refund Rate Trend Over Time
-- Business Question: Is our refund rate improving over time?
-- ============================================================
WITH monthly_refunds AS (
    SELECT
        DATE_TRUNC('month', o.created_at)       AS order_month,
        COUNT(DISTINCT o.order_id)              AS total_orders,
        COUNT(DISTINCT r.order_item_refund_id)  AS total_refunds,
        ROUND(
            COUNT(DISTINCT r.order_item_refund_id)::DECIMAL /
            COUNT(DISTINCT o.order_id) * 100, 2
        )                                       AS refund_rate_pct
    FROM orders o
    LEFT JOIN order_item_refunds r ON o.order_id = r.order_id
    GROUP BY DATE_TRUNC('month', o.created_at)
)
SELECT
    order_month,
    total_orders,
    total_refunds,
    refund_rate_pct,
    LAG(refund_rate_pct) OVER
        (ORDER BY order_month)                  AS prev_month_refund_rate,
    ROUND(
        refund_rate_pct - LAG(refund_rate_pct)
            OVER (ORDER BY order_month)
    , 2)                                        AS refund_rate_change
FROM monthly_refunds
ORDER BY order_month;


-- ============================================================
-- QUERY 8: Customer Segmentation by Spending
-- Business Question: Who are our high, medium, low value customers?
-- ============================================================
WITH customer_spending AS (
    SELECT
        user_id,
        COUNT(order_id)                         AS total_orders,
        SUM(price_usd)                          AS total_spent,
        NTILE(3) OVER (
            ORDER BY SUM(price_usd) DESC
        )                                       AS spending_tier
    FROM orders
    GROUP BY user_id
)
SELECT
    CASE spending_tier
        WHEN 1 THEN 'High Value'
        WHEN 2 THEN 'Medium Value'
        WHEN 3 THEN 'Low Value'
    END                                         AS customer_segment,
    COUNT(user_id)                              AS total_customers,
    ROUND(AVG(total_orders), 2)                 AS avg_orders,
    ROUND(AVG(total_spent), 2)                  AS avg_spent,
    SUM(total_spent)                            AS segment_revenue
FROM customer_spending
GROUP BY spending_tier
ORDER BY spending_tier;


-- ================================================================
-- ████████████████████████████████████████████████████████████████
--   STEP 5 : STORED PROCEDURES & TRIGGERS
-- ████████████████████████████████████████████████████████████████
-- ================================================================

-- ============================================================
-- STORED PROCEDURE 1: Get Product Sales Summary
-- Business Use: Pull sales summary for any product by name
-- ============================================================
CREATE OR REPLACE PROCEDURE get_product_sales_summary(
    IN p_product_name VARCHAR(100)
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        p.product_name,
        COUNT(DISTINCT o.order_id)              AS total_orders,
        SUM(oi.price_usd)                       AS total_revenue,
        SUM(oi.cogs_usd)                        AS total_cost,
        SUM(oi.price_usd - oi.cogs_usd)         AS total_profit,
        ROUND(AVG(oi.price_usd), 2)             AS avg_selling_price,
        ROUND(
            SUM(oi.price_usd - oi.cogs_usd) /
            SUM(oi.price_usd) * 100, 2
        )                                        AS profit_margin_pct
    FROM products p
    JOIN order_items oi  ON p.product_id = oi.product_id
    JOIN orders o        ON oi.order_id = o.order_id
    WHERE LOWER(p.product_name) = LOWER(p_product_name);
END;
$$;
-- CALL get_product_sales_summary('The Original Mr. Fuzzy');


-- ============================================================
-- STORED PROCEDURE 2: Get Monthly Revenue Report
-- Business Use: Revenue report for any given year
-- ============================================================
CREATE OR REPLACE PROCEDURE get_monthly_revenue_report(
    IN p_year INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        DATE_TRUNC('month', created_at)         AS order_month,
        COUNT(DISTINCT order_id)                AS total_orders,
        SUM(price_usd)                          AS total_revenue,
        SUM(price_usd - cogs_usd)               AS total_profit,
        ROUND(AVG(price_usd), 2)                AS avg_order_value,
        SUM(items_purchased)                    AS total_items_sold
    FROM orders
    WHERE EXTRACT(YEAR FROM created_at) = p_year
    GROUP BY DATE_TRUNC('month', created_at)
    ORDER BY order_month;
END;
$$;
-- CALL get_monthly_revenue_report(2014);


-- ============================================================
-- STORED PROCEDURE 3: Get Refund Analysis by Date Range
-- Business Use: Refund data between any two dates
-- ============================================================
CREATE OR REPLACE PROCEDURE get_refund_analysis(
    IN p_start_date DATE,
    IN p_end_date   DATE
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        p.product_name,
        COUNT(DISTINCT oi.order_item_id)        AS total_items_sold,
        COUNT(DISTINCT r.order_item_refund_id)  AS total_refunds,
        SUM(COALESCE(r.refund_amount_usd, 0))   AS total_refund_amount,
        ROUND(
            COUNT(DISTINCT r.order_item_refund_id)::DECIMAL /
            NULLIF(COUNT(DISTINCT oi.order_item_id), 0) * 100, 2
        )                                        AS refund_rate_pct
    FROM products p
    LEFT JOIN order_items oi        ON p.product_id = oi.product_id
    LEFT JOIN order_item_refunds r  ON oi.order_item_id = r.order_item_id
    WHERE oi.created_at BETWEEN p_start_date AND p_end_date
    GROUP BY p.product_name
    ORDER BY refund_rate_pct DESC;
END;
$$;
-- CALL get_refund_analysis('2014-01-01', '2014-12-31');


-- ============================================================
-- STORED PROCEDURE 4: Get Traffic Source Performance
-- Business Use: Traffic analysis for any given time period
-- ============================================================
CREATE OR REPLACE PROCEDURE get_traffic_performance(
    IN p_start_date DATE,
    IN p_end_date   DATE
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        COALESCE(ws.utm_source, 'direct')       AS traffic_source,
        COALESCE(ws.utm_campaign, 'none')       AS campaign,
        ws.device_type,
        COUNT(DISTINCT ws.website_session_id)   AS total_sessions,
        COUNT(DISTINCT o.order_id)              AS total_orders,
        ROUND(
            COUNT(DISTINCT o.order_id)::DECIMAL /
            NULLIF(COUNT(DISTINCT ws.website_session_id), 0) * 100, 2
        )                                        AS conversion_rate_pct,
        SUM(o.price_usd)                        AS total_revenue
    FROM website_sessions ws
    LEFT JOIN orders o ON ws.website_session_id = o.website_session_id
    WHERE ws.created_at BETWEEN p_start_date AND p_end_date
    GROUP BY
        COALESCE(ws.utm_source, 'direct'),
        COALESCE(ws.utm_campaign, 'none'),
        ws.device_type
    ORDER BY total_revenue DESC;
END;
$$;
-- CALL get_traffic_performance('2014-01-01', '2014-12-31');


-- ============================================================
-- TRIGGER SETUP: Refund Audit Log Table
-- ============================================================
CREATE TABLE IF NOT EXISTS refund_audit_log (
    log_id                  SERIAL          PRIMARY KEY,
    order_item_refund_id    INT             NOT NULL,
    order_id                INT             NOT NULL,
    refund_amount_usd       DECIMAL(6,2)    NOT NULL,
    action_type             VARCHAR(10)     NOT NULL,
    action_timestamp        TIMESTAMP       NOT NULL DEFAULT NOW(),
    performed_by            VARCHAR(50)     DEFAULT CURRENT_USER
);


-- ============================================================
-- TRIGGER 1: Log Every New Refund Automatically
-- ============================================================
CREATE OR REPLACE FUNCTION log_new_refund()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO refund_audit_log (
        order_item_refund_id, order_id, refund_amount_usd,
        action_type, action_timestamp, performed_by
    ) VALUES (
        NEW.order_item_refund_id, NEW.order_id, NEW.refund_amount_usd,
        'INSERT', NOW(), CURRENT_USER
    );
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_log_new_refund
    AFTER INSERT ON order_item_refunds
    FOR EACH ROW EXECUTE FUNCTION log_new_refund();


-- ============================================================
-- TRIGGER 2: Prevent Negative Refund Amounts
-- ============================================================
CREATE OR REPLACE FUNCTION validate_refund_amount()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.refund_amount_usd <= 0 THEN
        RAISE EXCEPTION
            'Invalid refund amount: %. Refund must be greater than zero.',
            NEW.refund_amount_usd;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_validate_refund_amount
    BEFORE INSERT ON order_item_refunds
    FOR EACH ROW EXECUTE FUNCTION validate_refund_amount();


-- ============================================================
-- TRIGGER 3: Prevent Refund Exceeding Original Item Price
-- ============================================================
CREATE OR REPLACE FUNCTION validate_refund_vs_price()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_original_price DECIMAL(6,2);
BEGIN
    SELECT price_usd INTO v_original_price
    FROM order_items
    WHERE order_item_id = NEW.order_item_id;

    IF NEW.refund_amount_usd > v_original_price THEN
        RAISE EXCEPTION
            'Refund amount % exceeds original item price of %.',
            NEW.refund_amount_usd, v_original_price;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_validate_refund_vs_price
    BEFORE INSERT ON order_item_refunds
    FOR EACH ROW EXECUTE FUNCTION validate_refund_vs_price();


-- ================================================================
-- ████████████████████████████████████████████████████████████████
--   STEP 6 : PERFORMANCE OPTIMIZATION & INDEXING
-- ████████████████████████████████████████████████████████████████
-- ================================================================

-- ============================================================
-- WHY DO WE NEED INDEXES?
-- Without indexes PostgreSQL does a SEQUENTIAL SCAN meaning
-- it reads EVERY row in the table to find what you need.
-- With an index it jumps directly to the right row.
-- Think of it like a book index vs reading every page!
-- ============================================================

-- ============================================================
-- SECTION 2: CHECK QUERY PERFORMANCE BEFORE INDEXES
-- ⚠️ IMPORTANT: Run this BEFORE executing index creation below
-- ============================================================
EXPLAIN ANALYZE
SELECT * FROM orders
WHERE created_at BETWEEN '2014-01-01' AND '2014-12-31';


-- ============================================================
-- INDEXES ON orders TABLE
-- Most queried table — needs the most optimization
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_orders_created_at         ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_orders_user_id            ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_primary_product_id ON orders (primary_product_id);
CREATE INDEX IF NOT EXISTS idx_orders_website_session_id ON orders (website_session_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_created       ON orders (user_id, created_at);

-- ============================================================
-- INDEXES ON order_items TABLE
-- 40,025 rows — most critical JOIN table to optimize
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_order_items_order_id      ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id    ON order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_created_at    ON order_items (created_at);
CREATE INDEX IF NOT EXISTS idx_order_items_product_created ON order_items (product_id, created_at);

-- ============================================================
-- INDEXES ON order_item_refunds TABLE
-- 1,731 rows — smallest table, indexed for JOIN and date performance
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_refunds_order_id          ON order_item_refunds (order_id);
CREATE INDEX IF NOT EXISTS idx_refunds_order_item_id     ON order_item_refunds (order_item_id);
CREATE INDEX IF NOT EXISTS idx_refunds_created_at        ON order_item_refunds (created_at);

-- ============================================================
-- INDEXES ON website_sessions TABLE
-- 472,871 rows — second largest table, critical for traffic analysis
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_sessions_created_at           ON website_sessions (created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id              ON website_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_utm_source           ON website_sessions (utm_source);
CREATE INDEX IF NOT EXISTS idx_sessions_utm_source_campaign  ON website_sessions (utm_source, utm_campaign);
CREATE INDEX IF NOT EXISTS idx_sessions_device_created       ON website_sessions (device_type, created_at);

-- ============================================================
-- INDEXES ON website_pageviews TABLE
-- Largest table in the dataset — 1,188,124 rows — needs careful indexing
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_pageviews_session_id      ON website_pageviews (website_session_id);
CREATE INDEX IF NOT EXISTS idx_pageviews_url             ON website_pageviews (pageview_url);
CREATE INDEX IF NOT EXISTS idx_pageviews_url_created     ON website_pageviews (pageview_url, created_at);
CREATE INDEX IF NOT EXISTS idx_pageviews_created_at      ON website_pageviews (created_at);

-- ============================================================
-- VERIFY ALL INDEXES WERE CREATED
-- ============================================================
SELECT
    tablename,
    COUNT(*)                        AS total_indexes,
    STRING_AGG(indexname, ', ')     AS index_names
FROM pg_indexes
WHERE schemaname = 'public'
AND tablename IN (
    'orders', 'order_items', 'order_item_refunds',
    'website_sessions', 'website_pageviews'
)
GROUP BY tablename
ORDER BY tablename;

-- ============================================================
-- CHECK QUERY PERFORMANCE AFTER INDEXES — compare with before!
-- ============================================================
EXPLAIN ANALYZE
SELECT * FROM orders
WHERE created_at BETWEEN '2014-01-01' AND '2014-12-31';

EXPLAIN ANALYZE
SELECT
    p.product_name,
    COUNT(DISTINCT o.order_id)      AS total_orders,
    SUM(oi.price_usd)               AS total_revenue
FROM orders o
JOIN order_items oi  ON o.order_id = oi.order_id
JOIN products p      ON oi.product_id = p.product_id
WHERE o.created_at BETWEEN '2014-01-01' AND '2014-12-31'
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- ============================================================
-- WHEN NOT TO USE INDEXES
-- ============================================================
-- ❌ DON'T index every column — slows INSERT/UPDATE/DELETE
-- ❌ DON'T index small tables like products (only 4 rows)
-- ❌ DON'T index low cardinality columns (TRUE/FALSE only)
-- ✅ DO index columns in WHERE clauses
-- ✅ DO index columns in JOIN conditions
-- ✅ DO index columns in ORDER BY and GROUP BY
-- ✅ DO use composite indexes for multi-column filters

-- ============================================================
-- DROP INDEXES IF NEEDED
-- Pattern: DROP INDEX IF EXISTS <index_name>;
-- ============================================================
-- DROP INDEX IF EXISTS idx_orders_created_at;
-- DROP INDEX IF EXISTS idx_orders_user_id;
-- DROP INDEX IF EXISTS idx_orders_primary_product_id;
-- DROP INDEX IF EXISTS idx_orders_website_session_id;
-- DROP INDEX IF EXISTS idx_orders_user_created;
-- DROP INDEX IF EXISTS idx_order_items_order_id;
-- DROP INDEX IF EXISTS idx_order_items_product_id;
-- DROP INDEX IF EXISTS idx_order_items_created_at;
-- DROP INDEX IF EXISTS idx_order_items_product_created;
-- DROP INDEX IF EXISTS idx_refunds_order_id;
-- DROP INDEX IF EXISTS idx_refunds_order_item_id;
-- DROP INDEX IF EXISTS idx_refunds_created_at;
-- DROP INDEX IF EXISTS idx_sessions_created_at;
-- DROP INDEX IF EXISTS idx_sessions_user_id;
-- DROP INDEX IF EXISTS idx_sessions_utm_source;
-- DROP INDEX IF EXISTS idx_sessions_utm_source_campaign;
-- DROP INDEX IF EXISTS idx_sessions_device_created;
-- DROP INDEX IF EXISTS idx_pageviews_session_id;
-- DROP INDEX IF EXISTS idx_pageviews_url;
-- DROP INDEX IF EXISTS idx_pageviews_url_created;
-- DROP INDEX IF EXISTS idx_pageviews_created_at;

-- ================================================================
--  END OF PROJECT | Maven Fuzzy Factory | Saket Tripathi | 2026
-- ================================================================
